import { describe, expect, it } from 'vitest';
import { hmr } from '../lib/hmr';

// Regression test: the hot-component wrapper generated by `getHotComponent`
// imports `@glimmer/reference`, `@glimmer/runtime`, `@ember/destroyable` and
// `@glimmer/manager`. Those wrappers are generated/served on demand, so they
// are never in the static graph Vite's dependency scanner crawls on the first
// pass. Unless the plugin pre-declares them, the browser requests them on
// boot, Vite discovers "new" deps and triggers a re-optimize + full page
// reload.
//
// The deps must be declared as the Embroider-rewritten `ember-source/...`
// subpaths — the bare `@glimmer/reference` etc. specifiers the wrapper writes
// cannot be resolved by optimizeDeps.include.
describe('hmr() optimizeDeps declaration', () => {
  const callConfig = (
    plugin: ReturnType<typeof hmr>,
    mode: string,
  ) => {
    const hook = plugin.config as (
      config: unknown,
      env: { mode: string; command: string },
    ) => { optimizeDeps?: { include?: string[] } } | undefined;
    return hook({}, { mode, command: 'serve' });
  };

  it('pre-bundles the wrapper deps the scanner cannot see (enabled mode)', () => {
    const result = callConfig(hmr(['development']), 'development');

    expect(result?.optimizeDeps?.include).toEqual([
      'ember-source/@glimmer/reference/index.js',
      'ember-source/@glimmer/runtime/index.js',
      'ember-source/@ember/destroyable/index.js',
      'ember-source/@glimmer/manager/index.js',
    ]);
  });

  it('does not touch optimizeDeps when HMR is disabled for the mode', () => {
    const result = callConfig(hmr(['development']), 'production');

    expect(result).toBeUndefined();
  });
});
