# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  schedule:
    - cron: "0 9 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - run: pnpm i
      - run: pnpm run build || echo "ignore failures for now"
      - run: pnpm run test
      - run: pnpm view "ember-vite-hmr@$(cat package.json | jq -r '.version')" || npm publish
        if: github.ref == 'refs/heads/main'

